name: GitHub Actions Demo
on: [workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: echo "$GITHUB_REPOSITORY_OWNER"
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '8'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
      - uses: actions/setup-ty
      - run: ./gradlew :typescriptPreCommit  -i
