name: GitHub Actions Demo
on: [workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: echo "$GITHUB_REPOSITORY_OWNER"
      - uses: actions/checkout@v3
      - run: ./gradlew :typescriptPreCommit  -i
