name: Upload to GCS Example

on:
  workflow_dispatch:


jobs:
  upload_object:
    runs-on: [self-hosted,ubuntu-20.04]

    steps:
      - name: Install java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: Run Gradle Command
        shell: bash
        run: |
          # Removing settings.xml is a workaround to avoid a decryption issue
          # of Beam's gradle-command-action plugin and github's provided
          # maven settings.xml file
          rm ~/.m2/settings.xml
      - name: Download Generic Artifact
        uses: actions/checkout@v3
        with:
          repository: apache/beam
          ref: master
      
      - name: Build project
        run: ./gradlew build
      
      - name: Copy JAR to bucket
        env:
          BUCKET_NAME: ${{secrets.BUCKET_NAME}}
        run: gcloud alpha storage cp --recursive ./build/libs/ gs://$BUCKET_NAME
      
      - name: Checking bucket contents
        env:
          BUCKET_NAME: ${{secrets.BUCKET_NAME}}
        run: gcloud alpha storage ls --recursive gs://$BUCKET_NAME/**
      