name: Upload to GCS Example

on:
  workflow_dispatch:


jobs:
  upload_object:
    runs-on: [self-hosted,ubuntu-20.04]

    steps:
      - name: Setup Go 
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true 
      - name: Setup python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Java
        uses: actions/setup-java@v3
        with: 
          distribution: 'temurin'
          java-version: |
            8
            11
      - name: Exporting Java_HOME to Java 8
        run: echo "JAVA_HOME=${JAVA_HOME_8_X64}" >> $GITHUB_ENV
      - name: Run Gradle Command
        shell: bash
        run: |
          # Removing settings.xml is a workaround to avoid a decryption issue
          # of Beam's gradle-command-action plugin and github's provided
          # maven settings.xml file
          rm ~/.m2/settings.xml
      - name: Download Generic Artifact
        uses: actions/checkout@v3
        with:
          repository: apache/beam
          ref: master
      
      - name: Build project
        run: ./gradlew build -PisRelease  --scan --stacktrace --continue  -x ':website:createDockerContainer' -x ':website:startDockerContainer' -x ':website:buildLocalWebsite' -x ':website:initGitSubmodules' -x ':website:installDependencies' -x ':website:buildCodeSamples' -x ':website:setupDockerContainer' -x ':website:stopAndRemoveDockerContainer' -x ':website:cleanWebsite' -x ':website:serveWebsite' -x ':website:testWebsite'
      
      - name: Copy JAR to bucket
        env:
          BUCKET_NAME: ${{secrets.BUCKET_NAME}}
        run: gcloud alpha storage cp --recursive ./build/libs/ gs://$BUCKET_NAME
      
      - name: Checking bucket contents
        env:
          BUCKET_NAME: ${{secrets.BUCKET_NAME}}
        run: gcloud alpha storage ls --recursive gs://$BUCKET_NAME/**
      